services:
  app:
    build:
      context: .
      dockerfile: src/rag_eval/Dockerfile
      target: runtime

    container_name: rag-eval-dev
    command: uvicorn rag_eval.main:app --host 0.0.0.0 --port 8000 --reload

    ports:
      - "8000:8000"

    volumes:
      - ./src:/app/src
      - .env:/app/.env

    env_file:
      - .env

    # depends_on:
    #   - db:
    #     condition: service_healthy

    networks:
      - backend
  # db:
  #   image: postgres:15-alpine
  #   container_name: rag-eval-db-dev

  #   volumes: postgres_data:/var/lib/postgresql/data

  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: devpassword
  #     POSTGRES_DB: rageval

  #   networks:
  #     - backend

  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U postgres" ]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
