
name: CI pipeline rag-eval

on: 
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]
    workflow_dispatch:  # Allow manual triggers


permissions:
    contents: read
    packages: write
    security-events: write


env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    lint:
        name: linting the code
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: install uv
              uses: astral-sh/setup-uv@v4

            - name: install dependencies
              run: uv sync --frozen

            - name: Run ruff linter
              run: uv run ruff check .

            - name: Run ruff formatter check
              run: uv run ruff format --check .

    test:
        name: Unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'
            
            - name: intal uv
              uses: astral-sh/setup-uv@v4

            - name: install dependencies
              run: uv sync --frozen

            - name: Run tests
              run: uv run pytest
    # build:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4

    #         - name: setup python
    #           uses: actions/setup-python@v5
    #           with:
    #             python-version: '3.13'
            
    #         - name: install uv